vich_uploader:
    db_driver: orm

    mappings:
      cours_images:
            uri_prefix: /cours_images
            upload_destination: '%kernel.project_dir%/public/cours_images'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
            delete_on_remove: true
            delete_on_update: true 
